using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Car_Scrapper
{
    public static class Variables
    {
        public static List<string> ExcelColumns = new List<string>(new string[] {
            "userId",
            "dpId",
            "email",
            "listingId",
            "title",
            "categoryLevel1",
            "categoryLevel2",
            "categoryLevel3",
            "mcat",
            "newOrUsed",
            "auctionOrClassified",
            "sellerId",
            "sellerRegion",
            "sellerDistrict",
            "sellerInTrade",
            "isBuyNow",
            "isPayNow",
            "buyNowPrice",
            "mustPickUp",
            "freeShipping",
            "url",
            "isExpired",
            "hasVideo",
            "hasPhotos",
            "tracked",
            "pageName",
            "isFeatured",
            "isSuperFeatured",
            "hasGtinCode",
            "wasPrice",
            "motorsKilometers",
            "motorsMake",
            "motorsType",
            "motorsModel",
            "motorsYear",
            "motorsListType",
            "motorsDealerId",
            "motorsTradingName",
            "motorsAutobaseVehicleId",
            "propertyMapShown",
            "propertyMapHasSchoolsView",
            "propertyMapHasBoundaryView",
            "propertyMapHasStreetView",
            "jobsAgent",
            "subtitle",
            "Asking Price",
            "Listing Date",
            "On Road Costs",
            "Number Plate",
            "Body",
            "Fuel Type",
            "Engine",
            "Transmisssion",
            "4WD",
            "History",
            "Regitration Expires",
            "WOF Expires",
            "Stereo description",
            "Model Detail",
            "Features",
            "Fuel Economy",
            "Safaty Rating",
            "Description",
            "Classified Auctions - Feedback",
            "Classified Auctions - Phone",
            "Classified Auctions - Mobile",
            "Classified Auctions - Expiry Date",
            "Current Bid", "Reserve Met",
            "Engine Size", "Import History",
            "Classified Auctions – Dealer Name",
            "Classified Auctions – Dealer City",
            "Classified Auctions – Dealer Phone",
            "Classified Auctions – Dealer Name 1",
            "Classified Auctions – Phone 1",
            "Auction Sale – Seller Mobile",
            "Starting Bid",
            "Buy Now",
            "Reserve Not Met" });

        public static Dictionary<string, string> IDList = new Dictionary<string, string>
        {
            { "ListingTitle_classifiedTitlePrice", "Asking Price" },
            { "ListingTitle_titleTime", "Listing Date" },
            { "ListingDescription_ListingDescription", "Description" },
            { "ClassifiedActions_PositiveFeedback", "Classified Auctions - Feedback" },
            { "ClassifiedActions_SellerPhone", "Classified Auctions - Phone" },
            { "ClassifiedActions_SellerMobile", "Classified Auctions - Mobile" },
            { "ClassifiedActions_Expires", "Classified Auctions - Expiry Date" },
            { "BidBuyNow_bidCurrentAmount", "Current Bid" },
            { "ClassifiedActions_DealerName", "Classified Auctions – Dealer Name" },
            { "ClassifiedActions_DealerCity", "Classified Auctions – Dealer City" },
            { "ClassifiedActions_DealerPhoneDiv", "Classified Auctions – Dealer Phone" },
            { "ClassifiedActions_DealerAgentName1", "Classified Auctions – Dealer Name 1" },
            { "ClassifiedActions_DealerAgentPhone1", "Classified Auctions – Phone 1" },
            { "AuctionSaleDetail_SellerMobile", "Auction Sale – Seller Mobile" },
            { "QuickBid_bidFormBid", "Starting Bid" },
            { "BidBuyNow_bidReserveNotMet", "Reserve Not Met" },
            { "BidBuyNow_bidReserveMet", "Reserve Met" },
        };
    }
}
